### ISSUE TITLE
Problems in watching files recursively

### ISSUE THREAD

**Issue by dozaza** [emcrisostomo/fswatch#138]
Hi, 

I got something very strange in watching file with `Ubuntu 16.04` and `fswatch 1.9.3 `.

First, I do some test in an empty directory, run `fswatch -drx ./ | grep -E "(Created|Updated|Removed)"` , `mkdir test`, `touch test/a.sh`. It gives me the right results:
`/home/baoan/dev/git/test_sync/test Created`
`/home/baoan/dev/git/test_sync/test/a.sh Created`
`/home/baoan/dev/git/test_sync/test/a.sh Updated` 

But when I try to do the same thing in my project directory which contains about 170950 files counting by `ls -lR | wc -l`, I get nothing in console.

So, I think may be its the problem of file numbers & performance?

Thx.

**Comment by dozaza** [comment]
I think I found the reason.

I tried to use fswatch under a directory which contains about 8260 files. 

I waited for about 15 seconds to get the response of fswatch when creating a new file by `touch`.

So I think the reason why there is no response in my first post, is that fswatch is doing some initialization (loop directory recursively).

Is there any solution of big/huge file system watching?

**Comment by emcrisostomo** [comment]
Hi, Linux `inotify` API returns events about first-level children of a directory. Hence, if you're recursively watching a directory hierarchy, `fswatch` will navigate through it and add an `inotify` watch for each directory. If you have a lot of files into the hierarchy there's a certain overhead because each file is `stat()`-ted.

I've made some test on dockerized instances of Debian, Ubuntu and Alpine and I find `fswatch` to receive the first events in less than 1 second when recursively scanning a hierarchy of 10.000 files. Using instead a randomly created hierarchy containing 100.000 files, `fswatch` finishes creating the watches in approximately 8 seconds. All these tests were run in a 2011 machine.

Are you using a particularly slow machine?
