### ISSUE TITLE
Batched notifications in OS X with git branch change

### ISSUE THREAD

**Issue by karptonite** [emcrisostomo/fswatch#139]
I'm using fswatch 1.9.3 on OS X 10.11.6 with git 2.10.0. I'm watching the top level of a git repository with the following command:
`fswatch -o -l 5 --exclude "[reasonable excludes]" "/path/to/repo"`
When I checkout a different branch of the repo, I immediately get the following from fswatch:
32
32
32
32
32
32
32
13
9
This is not the same notification over and over--rather (I know from running it without the `-o` flag), several hundred files have changed at once, but fswatch is reporting the changes in batches of 32 files at most. Should these not be grouped in one batch?

**Comment by emcrisostomo** [comment]
Hi @karptonite,

`fswatch` has no clear way to group events received by the operating system because they are file system change events, and they have no time boundaries. If the OS X API returns them on batches of a specific size is an implementation detail. Even if it that size could be raised, which I doubt (but I'll check), you could hit anyway the new max, and we'll be back at square one.

**Comment by karptonite** [comment]
Thank you. That makes sense. It may be that fswatch is not the right tool for what I am trying to do, and I am now investigating watchman as an alternative.

**Comment by phs** [comment]
If you came here looking for a way to make `fswatch` report one event per latency window instead of per (fixed-size) batch, I've found a bash construction to do so.  Recent bash versions allow fractional timeouts on the `read`, but this snippet will work with bash as shipped with OSX.

```
fswatch --one-per-batch --latency=0.1 . | \
while read batch
do
  # We know we have work, now eagerly consume any remaining events
  while read -t 1 batch
  do
    :
  done

  # And do the work
  process_event
done
```
