### ISSUE TITLE
How to make Event Filters work?

### ISSUE THREAD

**Issue by AbdulHadiParsdorfer** [emcrisostomo/fswatch#153]
Hi,

I found following in your manual:

> 4.9 Filtering by Event Type
> 
> Events can be filtered by event type passing fswatch a list of event type names to accept using the --event option:
> 
> $ fswatch -x --event Created --event Removed ~
> 
> If no event type filters are specified fswatch will accept events of any type; on the other hand, as soon as a filter is specified, only events with a matching type will be accepted.

I applied it as following on a OS X machine:

`fswatch -0 -x --event Created --event Updated --event Renamed -Ie '.*\.*$' -i '.*\.mp4$' /path/to/folder | xargs -0 -n 1 /path/to/script.sh`

But the filter does not work. If I remove an item the event is passed over to the script which should not happen if I understood your description correctly.

How can I solve the problem?
Thank you.

**Comment by emcrisostomo** [comment]
Hi,

Since you don't clearly specify the order of events that trigger the problem, I cannot but guess what's happening.

I think the problem is a consequence of how OS X delivers events about the same path that happen in a short period of time. For example: if you create a new file `x`, you'll receive (using `fswatch` jargon from now on) a `Created` event for  `x`. If you then remove `x`, OS X may deliver both `Created` and `Removed` events for `x`.

If you have further information to share, please reopen the issue.

**Comment by AbdulHadiParsdorfer** [comment]
Hi,

thank you for your answer.
I want to use fswatch for a watch folder to upload videos with s3cmd.
I want to filter the events `Created`, `MovedTo`, `Renamed` and `Updated`.
`Created` works for new created files. `MovedTo` does not give any event and `Updated` throws only an event if you create a new file. `Renamed` gives for almost everything an event. If you move the file in, if you move it out, when you remove it and when you rename the file you get even two events. One for the old name and one for the new name. 

I only want to upload new videos (created or added), modified ones or renamed ones. 
Without event filter I get to many events which I don't want and which causes errors in the script.
But with the given event filters and there functionality I can only filter the `Created` event.
 
Is fswatch able to filter those events? How can I solve this problem?

Thank you.

**Comment by unoexperto** [comment]
@emcrisostomo Enrico, could you suggest how to filter output by event type on Ubuntu/Linux ?
