### ISSUE TITLE
Can not exclude exact file

### ISSUE THREAD

**Issue by amrography** [emcrisostomo/fswatch#187]
Hi, 
I am trying to exclude the build file (which been built with another bash command) but it's not excluded. So I go through infinity loop

```
build)
....
watch)
     fun build
     fswatch -Ie "^final.php$" -o ~/path/files | fun watch
```

I went through the documentations but didn't find an example on that

**Comment by emcrisostomo** [comment]
Hi,

I frankly haven't understood exactly what it is that you're trying to accomplish. What's the path of the file you're trying to exclude? If it's `final.php`, then the regular expression you're specifying will not match any path, because the paths reported by `fswatch` will start with `~/path/files` (actually, its absolute path).

**Comment by amrography** [comment]
So I should exclude ~/path/files/final.php 
like this : `-Ie "^~\/path\/files\/final.php$` ?

**Comment by t3hk0d3** [comment]
@amrography 
I think `-Ie "\/files\/final\.php$`

**Comment by amrography** [comment]
@t3hk0d3 Thanks for you help, but this didn't work

I tried to exclude all *.php files fswatch still watching them
`fswatch -Ie ".*\.php$" ~/path/files | fun watch`

**Comment by emcrisostomo** [comment]
I just can't replicate your problem. Running `fswatch -Ie ".*\.php$" ~/temp` correctly ignores files whose name end with `php`. You still fail to provide some example output though (without the pipe to any other process). Also, it's important to know which monitor you're using.
