### ISSUE TITLE
How to get the PDF documentation

### ISSUE THREAD

**Issue by meator** [emcrisostomo/fswatch#292]
Hello. https://github.com/emcrisostomo/fswatch/blob/master/README.md?plain=1#L212-L214 encourages package managers to bundle the PDF documentation into the package but I wasn't able to find any instructions on how to do so. There aren't any instructions how to do so in README.md, README.gnu-build-system and `./configure --help`. The changelog pointed me to 85bca1116dce956d03915291f570293c4a8ce913 but that is no longer in README.

**Comment by meator** [comment]
It has been removed by 376de51f3746baf7706ddaec7633937e3b752ca9. Was it because `make pdf` should no longer be used?

**Comment by emcrisostomo** [comment]
Hello @meator. The wording has been simplified. The PDF documentation is built using standard Automake targets created when Texinfo documentation is present (`fswatch.texi`). Refer to Automake documentation to get the details you need about its mechanics. The short story is: if you have a TeX distribution and all the packages you need to create the PDF version of the Texinfo documentation, you can use `make pdf`. But since most people, and build environment nowadays, do not have a suitable TeX distribution, that target is not executed by default.

**Comment by meator** [comment]
Thanks!
