### ISSUE TITLE
Allow filtering by event type

### ISSUE THREAD

**Issue by emcrisostomo** [emcrisostomo/fswatch#46]

**Comment by RomeshA** [comment]
I'd like to second this, I'm writing a script to move newly-created files that are dropped remotely into a folder, but on Linux each file creation results in 4 events (only one of which is creation) - and it can also results in an event on the parent folder. So it's much harder to isolate just the created file

**Comment by lucianp** [comment]
Like the others have said, I think this feature would be extremely useful.
Most of the time we are only interested in actual file changes (`CREATE`, `CLOSE_WRITE`, `DELETE`, `MODIFY`, `MOVED_FROM`, `MOVED_TO`) and we would like to ignore read events (`OPEN`, `ISDIR`, `CLOSE_NOWRITE`, etc.).

I realize that it may not be trivial to implement this in a platform-independent manner, because the events probably differ from one platform to another.
A compromise solution could be to just add a way to filter read events from write events.

Thank you for all the hard work!

**Comment by emcrisostomo** [comment]
Hi @lucianp,

you're welcome and thanks, it's appreciated.

Yes, I agree it would be useful.  In fact, I'm reviewing the mappings between platform-specific events and "generic" fswatch events soon and implement this.

**Comment by emcrisostomo** [comment]
Hi all,

This issue has been fixed in [1.5.0][latest]. I'll prepare the OS X ports shortly.

[latest]: https://github.com/emcrisostomo/fswatch/releases/tag/1.5.0

**Comment by fanktom** [comment]
Hey @emcrisostomo, could you elaborate on how to use the event filters?

I tried
```
fswatch --event=CLOSE_WRITE files
```
which I expected to fire only on CLOSE_WRITE events.
Is that the intended behaviour? Unfortunately I could not find any information in the manuals except for:

```
--event name
      Filter event with the specified name.  This option can be used multiple times, one for each event name that must be included in the output.
```

Unfortunately, on my linux machine this just immediately exits.

**Comment by zachatrocity** [comment]
@fanktom hello from the future. 

Leaving this here incase anyone else is having issues using the event filters. I wasn't able to find the event names anywhere on github or the `man` page. 

After looking at the source I found the event names here in the [event.cpp](https://github.com/emcrisostomo/fswatch/blob/ba411e0d0fabcd5cbf0881f1380482e2f5ab9f47/libfswatch/src/libfswatch/c%2B%2B/event.cpp#L61C31-L75)

I was able to use the event filters like so:

```
fswatch --event "Updated" .  
```

For an even more specific example I used the filters combined with the `-i` flag to only watch for `.scss` files being `Updated` like so:

```
fswatch --event "Updated" -e ".*" -i "\\.scss$" .
```
