### ISSUE TITLE
Build fails on Ubuntu 14.04.1 LTS

### ISSUE THREAD

**Issue by dazzag24** [emcrisostomo/fswatch#58]
$ autoconf
configure.ac:31: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:45: error: possibly undefined macro: AM_INIT_AUTOMAKE
configure.ac:46: error: possibly undefined macro: AM_SILENT_RULES
configure.ac:47: error: possibly undefined macro: AM_PROG_AR
configure.ac:59: error: possibly undefined macro: AM_GNU_GETTEXT
configure.ac:60: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
configure.ac:71: error: possibly undefined macro: AM_CONDITIONAL

$ cat /etc/issue
Ubuntu 14.04.1 LTS \n \l

$ autoconf -V
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
http://gnu.org/licenses/gpl.html, http://gnu.org/licenses/exceptions.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

**Comment by sfinktah** [comment]
I think you could afford to place the text that says:

> A user who whishes to build fswatch should get a release tarball. A release tarball contains everything a user needs to build fswatch on his system 

in the README (in the git root).  I actually read with interest the history of fsw and fswatch, and thought I had read everything else, but alas half an hour of googling on AC_CONFIG_MACRO_DIRS bought me here, and I had to re-evaluate.

Excellent works on the program BTW.  I guess I just tend to pay more attention to README/INSTALL files I read in vim, rather than on the web.
