### ISSUE TITLE
Allow excluding file patterns by passing in a file

### ISSUE THREAD

**Issue by bengillies** [emcrisostomo/fswatch#60]
Basically what I'd like is to pass in my `.gitignore` file(s) and have it exclude everything that matches rather than specify everything via regexp.

**Comment by ricardobeat** [comment]
@emcrisostomo any updates on this?

**Comment by grayside** [comment]
globstar is supported by default on Bash 4

**Comment by emcrisostomo** [comment]
Hi @ricardobeat, I'm afraid this issue hasn't been worked on yet.

**Comment by fernandomora** [comment]
+1

**Comment by ricardobeat** [comment]
In the meantime, [git-check-ignore](https://git-scm.com/docs/git-check-ignore) allows deferring this logic to`git` itself: `fswatch . | while read file; do git check-ignore -q $file || echo $file; done`

**Comment by emcrisostomo** [comment]
Being able to exclude files is important so that `fswatch` can exert a lesser load on the system, especially when the monitor uses limited resources such as file descriptors. Trimming an otherwise huge file hierarchy is a feature that is definitely required. Maintaining the current implementation (a `fswatch`-specific syntax) is OK to me.

Having `fswatch` understand other exclude file types may be nice, but it's not only essential: the output can be filtered, how a user exactly wants. Furthermore, as @ricardobeat pointed out, in the case of `git` it's very easy to check a path against the ignore patterns.

I'm closing this issue and I'll probably add an example using `git check-ignore` to the documentation.

**Comment by Peeja** [comment]
I like the `git check-ignore` trick, but unless I'm missing something, there's no way to debounce/batch the changes that way, since you can't filter before batching. However, if Node.js is available, [`throttle-cli`](https://github.com/edi9999/throttle-cli) looks like it would cover it.
