### ISSUE TITLE
fswatch isn't following symbolic links

### ISSUE THREAD

**Issue by seaside98** [emcrisostomo/fswatch#87]
Fswatch does not follow symbolic links to watch events within the symbolic link. I am running 
```
fswatch -Lr /dir/with/symb/inside
```
I have also tried ```--follow-links```, with no results. Hopefully this isn't just an issue with me.

OSX yosemite
fswatch 1.4.7

**Comment by emcrisostomo** [comment]
I just tried to replicate your issues but I don't find any problem:

    % fswatch --version
    fswatch 1.4.7
    ...
    % mkdir ${HOME}/temp
    % ln -s ${HOME}/temp ${HOME}/mylink
    % fswatch -Lr ${HOME}/mylink

From another terminal:

    % touch ${HOME}/mylink/test.txt

and `fswatch` outputs (`${HOME}` is a placeholder):

    ${HOME}/temp/two.txt Created IsFile

Could you confirm you are affected by this problem?

**Comment by seaside98** [comment]
Perhaps I am using it wrong, is there not support for nested symbolic links? 

% ln -s ${HOME}/temp ${HOME}/folder/mylink 
% fswatch -Lr ${HOME}/folder

**Comment by emcrisostomo** [comment]
Symlink resolution is guaranteed when parsing command line arguments but then each monitor has its own characteristics. You are running `fswatch` on OS X and I assume you are using the FSEvents monitor: in this case, the `-L` option has no effect since the FSEvents API does not offer this behaviour.

Monitors using other APIs, such as kqueue and inotify, have to scan the file system anyway and adding this behaviour was straightforward.

**Comment by seaside98** [comment]
Ah, that explains it. Thank you very much!

**Comment by emcrisostomo** [comment]
You're welcome @seaside98
