### ISSUE TITLE
Strange behavior when using -print0 option

### ISSUE THREAD

**Issue by kpeterson11** [emcrisostomo/fswatch#97]
I'm noticing some strange behavior when using the -print0 option on my freebsd 9.3 install.  I'll use examples to explain it.

I run:

fswatch -0 -1 -r /media | while read event; do echo blah; done

I then touch a file in /media and fswatch exits with no error.  The word 'blah' is NOT printed.

I then run:

fswatch -1 -r /media | while read event; do echo blah; done

Then touch a file in /media and the word 'blah' is printed on the screen.

Is the intended behavior? I'm trying to use fswatch to watch my media directory and run some commands when a file is added.

I am using /bin/sh as the shell for my script.  I was using bash before and it did work fine when using -print0.

**Comment by emcrisostomo** [comment]
Hi @kpeterson11,

`read` reads *words* and it must be told how to appropriately read `fswatch` output. When using `-0`, you're telling `fswatch` to end lines with `\0` instead of `\n`. Try using:

```
fswatch -0 -1 -r /media | while IFS= read -d event ; do echo $event; done
```

Let us know.

**Comment by kpeterson11** [comment]
Using IFS doesn't help either.  I did try that before.  I should've mentioned that earlier.  I also can't use -d in read because I get a message saying -d is an invalid option.  I don't think sh's read supports that.  Bash does.

I tried all of these and they all output nothing when I touch /media.  I've also tried putting IFS after read and that didn't change anything.

# fswatch -0 -1 -r /media | while IFS= read event ; do echo $event; done
# fswatch -0 -1 -r /media | while IFS='' read event ; do echo $event; done
# fswatch -0 -1 -r /media | while IFS="" read event ; do echo $event; done

**Comment by emcrisostomo** [comment]
Hi @kpeterson11,

I'm sorry `IFS` won't do the trick here. `IFS` is used to break a line into fields (I put it because I consider it a good practice). The trick here is `-d`, which is used to specify the delimiter to be used for line splitting instead of `\n`. If your implementation of `read` doesn't have this feature, which you're right it's not portable, I'm afraid you'll have to find another way to split the lines emitted by `fswatch` using the `\0` character. At the moment I have no portable suggestion to give, but that's hardly a `fswatch` issue.

**Comment by kpeterson11** [comment]
Ok thanks! I wasn't sure if it was a weird bug with fswatch or not.  It turns out the sh shell doesn't play nice with the null character.  Since I'm using -1 to specify 1 event, not using -0 shouldn't cause any issues.
